<?php $authUser_NameSpace = new Zend_Session_Namespace('Myblog_Auth'); ?>
<div class="page-header">
    <h1>Welcome to My Blog</h1>
</div>
<div class="container">
    <?php if (isset($authUser_NameSpace->acl) && isset($authUser_NameSpace->user->role) && $authUser_NameSpace->acl->isAllowed($authUser_NameSpace->user->role, 'user', 'list')) { ?>
        <div class="row" id="posts"></div>
<?php } ?>
    <script type="text/javascript" src="/js/homepage/index.js"></script>
</div>