<script type="text/javascript" src="js/homepage/index.js"></script>
<div class="container">
    <form class="form-signup" action="/register" method="POST">
        <h2 class="form-signin-heading">Sign up</h2>
        <label for="inputName" class="sr-only">Name</label>
        <input type="text" name="inputName" id="inputName" class="form-control inputName" placeholder="Name" required autofocus>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="inputEmail" id="inputEmail" class="form-control inputEmail" placeholder="Email address" required>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="inputPassword" id="inputPassword" class="form-control inputPassword" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>